// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/obiwan007/usersrv/projectsrv/api/storage/ent/project"
	"github.com/obiwan007/usersrv/projectsrv/api/storage/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescDescription is the schema descriptor for description field.
	projectDescDescription := projectFields[0].Descriptor()
	// project.DefaultDescription holds the default value on creation for the description field.
	project.DefaultDescription = projectDescDescription.Default.(string)
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[1].Descriptor()
	// project.DefaultName holds the default value on creation for the name field.
	project.DefaultName = projectDescName.Default.(string)
	// projectDescClientid is the schema descriptor for clientid field.
	projectDescClientid := projectFields[2].Descriptor()
	// project.DefaultClientid holds the default value on creation for the clientid field.
	project.DefaultClientid = projectDescClientid.Default.(string)
	// projectDescUserid is the schema descriptor for userid field.
	projectDescUserid := projectFields[3].Descriptor()
	// project.DefaultUserid holds the default value on creation for the userid field.
	project.DefaultUserid = projectDescUserid.Default.(string)
	// projectDescMandantid is the schema descriptor for mandantid field.
	projectDescMandantid := projectFields[4].Descriptor()
	// project.DefaultMandantid holds the default value on creation for the mandantid field.
	project.DefaultMandantid = projectDescMandantid.Default.(string)
	// projectDescStatus is the schema descriptor for status field.
	projectDescStatus := projectFields[5].Descriptor()
	// project.DefaultStatus holds the default value on creation for the status field.
	project.DefaultStatus = projectDescStatus.Default.(string)
	// projectDescTags is the schema descriptor for tags field.
	projectDescTags := projectFields[6].Descriptor()
	// project.DefaultTags holds the default value on creation for the tags field.
	project.DefaultTags = projectDescTags.Default.(string)
	// projectDescTeam is the schema descriptor for team field.
	projectDescTeam := projectFields[7].Descriptor()
	// project.DefaultTeam holds the default value on creation for the team field.
	project.DefaultTeam = projectDescTeam.Default.(string)
}
