// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/obiwan007/usersrv/timersrv/api/storage/ent/schema"
	"github.com/obiwan007/usersrv/timersrv/api/storage/ent/timer"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	timerFields := schema.Timer{}.Fields()
	_ = timerFields
	// timerDescDescription is the schema descriptor for description field.
	timerDescDescription := timerFields[0].Descriptor()
	// timer.DefaultDescription holds the default value on creation for the description field.
	timer.DefaultDescription = timerDescDescription.Default.(string)
	// timerDescProjectid is the schema descriptor for projectid field.
	timerDescProjectid := timerFields[1].Descriptor()
	// timer.DefaultProjectid holds the default value on creation for the projectid field.
	timer.DefaultProjectid = timerDescProjectid.Default.(string)
	// timerDescTags is the schema descriptor for tags field.
	timerDescTags := timerFields[2].Descriptor()
	// timer.DefaultTags holds the default value on creation for the tags field.
	timer.DefaultTags = timerDescTags.Default.(string)
	// timerDescElapsedSeconds is the schema descriptor for elapsedSeconds field.
	timerDescElapsedSeconds := timerFields[5].Descriptor()
	// timer.DefaultElapsedSeconds holds the default value on creation for the elapsedSeconds field.
	timer.DefaultElapsedSeconds = timerDescElapsedSeconds.Default.(int)
	// timerDescIsBilled is the schema descriptor for IsBilled field.
	timerDescIsBilled := timerFields[6].Descriptor()
	// timer.DefaultIsBilled holds the default value on creation for the IsBilled field.
	timer.DefaultIsBilled = timerDescIsBilled.Default.(bool)
	// timerDescIsRunning is the schema descriptor for IsRunning field.
	timerDescIsRunning := timerFields[7].Descriptor()
	// timer.DefaultIsRunning holds the default value on creation for the IsRunning field.
	timer.DefaultIsRunning = timerDescIsRunning.Default.(bool)
	// timerDescUserid is the schema descriptor for userid field.
	timerDescUserid := timerFields[8].Descriptor()
	// timer.DefaultUserid holds the default value on creation for the userid field.
	timer.DefaultUserid = timerDescUserid.Default.(string)
	// timerDescMandantid is the schema descriptor for mandantid field.
	timerDescMandantid := timerFields[9].Descriptor()
	// timer.DefaultMandantid holds the default value on creation for the mandantid field.
	timer.DefaultMandantid = timerDescMandantid.Default.(string)
}
