// Code generated by entc, DO NOT EDIT.

package timerclient

const (
	// Label holds the string label denoting the timerclient type in the database.
	Label = "timer_client"
	// FieldID holds the string denoting the id field in the database.
	FieldID          = "id"          // FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription = "description" // FieldName holds the string denoting the name vertex property in the database.
	FieldName        = "name"        // FieldAddress holds the string denoting the address vertex property in the database.
	FieldAddress     = "address"     // FieldUserid holds the string denoting the userid vertex property in the database.
	FieldUserid      = "userid"      // FieldMandantid holds the string denoting the mandantid vertex property in the database.
	FieldMandantid   = "mandantid"

	// Table holds the table name of the timerclient in the database.
	Table = "timer_clients"
)

// Columns holds all SQL columns for timerclient fields.
var Columns = []string{
	FieldID,
	FieldDescription,
	FieldName,
	FieldAddress,
	FieldUserid,
	FieldMandantid,
}

var (
	// DefaultDescription holds the default value on creation for the description field.
	DefaultDescription string
	// DefaultName holds the default value on creation for the name field.
	DefaultName string
	// DefaultAddress holds the default value on creation for the address field.
	DefaultAddress string
	// DefaultUserid holds the default value on creation for the userid field.
	DefaultUserid string
	// DefaultMandantid holds the default value on creation for the mandantid field.
	DefaultMandantid string
)
