version: "2"

networks:
  app-tier:
    driver: bridge

services:
  zipkin:
    image: "jaegertracing/all-in-one:1.17"
    ports:
      - 9411:9411
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - app-tier
  etcd:
    image: "bitnami/etcd:latest"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier
  # etcdviewer:
  #   image: 'nikfoundas/etcd-viewer'
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - app-tier

  etcdbrowser:
    image: "registry.cn-hangzhou.aliyuncs.com/ringtail/lucas:0.0.2"
    ports:
      - 8080:8080
    environment:
      - ENDPOINTS=etcd:2379
    networks:
      - app-tier

  usersrv:
    build:
      context: .
      dockerfile: ./user_Dockerfile
    ports:
      - 10000:10000
    networks:
      - app-tier
    depends_on:
      - zipkin

  timersrv:
    build:
      context: .
      dockerfile: ./Dockerfile_timer
    ports:
      - 10001:10001
    networks:
      - app-tier
    depends_on:
      - zipkin

  projectsrv:
    build:
      context: .
      dockerfile: ./Dockerfile_project
    ports:
      - 10002:10002
    networks:
      - app-tier
    depends_on:
      - zipkin

  clientsrv:
    build:
      context: .
      dockerfile: ./Dockerfile_client
    ports:
      - 10003:10003
    networks:
      - app-tier
    depends_on:
      - zipkin

  gqlsrv:
    build:
      context: .
      dockerfile: ./gql_Dockerfile
    ports:
      - 8090:8090
    networks:
      - app-tier
    depends_on:
      - usersrv
      - timersrv
      - projectsrv
      - clientsrv
      - zipkin
    environment:
      - CLIENTID=${CLIENTID}
      - CLIENTSECRET=${CLIENTSECRET}
      - REDIRECT=${REDIRECT}

  frontend:
    build:
      context: ./frontend
      dockerfile: ./nginxDockerfile
    environment:
      - GRAPHQL=http://gqlsrv:8090
      - GQLSRV="gqlsrv"
      - ZIPKIN=http://zipkin:9411
    ports:
      - 3000:80
      - 3001:443
    networks:
      - app-tier
    depends_on:
      - gqlsrv
