version: "2"

networks:
  app-tier:
    driver: bridge

services:
  zipkin:
    image: "jaegertracing/all-in-one:1.18"
    ports:
      - 9411:9411
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - QUERY_BASE_PATH=/zipkin
    networks:
      - app-tier

  usersrv:
    build:
      context: .
      dockerfile: ./user_Dockerfile
    environment:
      - DBCONNECTIONUSER=user=postgres password=1234postgres1234 host=docker.for.mac.host.internal dbname=user port=5432 sslmode=disable
    ports:
      - 10000:10000
    networks:
      - app-tier
    depends_on:
      - zipkin

  timersrv:
    build:
      context: .
      dockerfile: ./Dockerfile_timer
    environment:
      - DBCONNECTIONTIMER=user=postgres password=1234postgres1234 host=docker.for.mac.host.internal dbname=timer port=5432 sslmode=disable
    ports:
      - 10001:10001
    networks:
      - app-tier
    depends_on:
      - zipkin

  projectsrv:
    build:
      context: .
      dockerfile: ./Dockerfile_project
    environment:
      - DBCONNECTIONPROJECT=postgres://postgres:1234postgres1234@192.168.178.32:5432/project?sslmode=disable
    ports:
      - 10002:10002
    networks:
      - app-tier
    depends_on:
      - zipkin

  clientsrv:
    build:
      context: .
      dockerfile: ./Dockerfile_client
    environment:
      - DBCONNECTIONCLIENT=postgres://postgres:1234postgres1234@192.168.178.32:5432/client?sslmode=disable
      - POSTGRES_HOST="host.docker.internal"
    ports:
      - 10003:10003
    networks:
      - app-tier
    depends_on:
      - zipkin

  gqlsrv:
    build:
      context: .
      dockerfile: ./gql_Dockerfile
    ports:
      - 8090:8090
    networks:
      - app-tier
    depends_on:
      - usersrv
      - timersrv
      - projectsrv
      - clientsrv
      - zipkin
    environment:
      - CLIENTID=${CLIENTID}
      - CLIENTSECRET=${CLIENTSECRET}
      - REDIRECT=${REDIRECT}

  frontend:
    build:
      context: ./frontend
      dockerfile: ./nginxDockerfile
    environment:
      - GRAPHQL=http://gqlsrv:8090
      - GQLSRV="gqlsrv"
      - ZIPKIN=http://zipkin:9411
    ports:
      - 3000:80
      - 3001:443
    networks:
      - app-tier
    depends_on:
      - gqlsrv
