FROM golang:1.14 as builder

ENV GO111MODULE=on
ENV CGO_ENABLED 0
ENV GOOS linux
ENV GOARCH=amd64 

RUN mkdir /build 
WORKDIR /build 

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN git version
RUN cd clientsrv/cli && go build -v -o clientsrv


FROM alpine

COPY --from=builder /build/clientsrv/ /app/
WORKDIR /app/cli
CMD ["./clientsrv"]