FROM golang:1.14 as builder

ENV GO111MODULE=on
ENV CGO_ENABLED 0
ENV GOOS linux
ENV GOARCH=amd64 

RUN mkdir /build 
WORKDIR /build 

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN git version
RUN cd timersrv/cli && go build -v -o timersrv


FROM alpine

COPY --from=builder /build/timersrv/ /app/
WORKDIR /app/cli
CMD ["./timersrv"]