version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zipkin:
    image: 'openzipkin/zipkin'
    ports:
      - 9411:9411
    networks:
      - app-tier
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier
  # etcdviewer:
  #   image: 'nikfoundas/etcd-viewer'
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - app-tier      

  etcdbrowser:
    image: 'registry.cn-hangzhou.aliyuncs.com/ringtail/lucas:0.0.2'
    ports:
      - 8080:8080
    environment:
      - ENDPOINTS=etcd:2379
    networks:
      - app-tier      

  myapp:
    build:
      context: .
      dockerfile: ./user_Dockerfile
    ports:
      - 10000:10000
    networks:
      - app-tier

