// Code generated by entc, DO NOT EDIT.

package project

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID          = "id"          // FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription = "description" // FieldName holds the string denoting the name vertex property in the database.
	FieldName        = "name"        // FieldClientid holds the string denoting the clientid vertex property in the database.
	FieldClientid    = "clientid"    // FieldUserid holds the string denoting the userid vertex property in the database.
	FieldUserid      = "userid"      // FieldMandantid holds the string denoting the mandantid vertex property in the database.
	FieldMandantid   = "mandantid"   // FieldStatus holds the string denoting the status vertex property in the database.
	FieldStatus      = "status"      // FieldTags holds the string denoting the tags vertex property in the database.
	FieldTags        = "tags"        // FieldTeam holds the string denoting the team vertex property in the database.
	FieldTeam        = "team"

	// Table holds the table name of the project in the database.
	Table = "projects"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldDescription,
	FieldName,
	FieldClientid,
	FieldUserid,
	FieldMandantid,
	FieldStatus,
	FieldTags,
	FieldTeam,
}

var (
	// DefaultDescription holds the default value on creation for the description field.
	DefaultDescription string
	// DefaultName holds the default value on creation for the name field.
	DefaultName string
	// DefaultClientid holds the default value on creation for the clientid field.
	DefaultClientid string
	// DefaultUserid holds the default value on creation for the userid field.
	DefaultUserid string
	// DefaultMandantid holds the default value on creation for the mandantid field.
	DefaultMandantid string
	// DefaultStatus holds the default value on creation for the status field.
	DefaultStatus string
	// DefaultTags holds the default value on creation for the tags field.
	DefaultTags string
	// DefaultTeam holds the default value on creation for the team field.
	DefaultTeam string
)
