// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/obiwan007/usersrv/usersrv/api/storage/ent/schema"
	"github.com/obiwan007/usersrv/usersrv/api/storage/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserid is the schema descriptor for userid field.
	userDescUserid := userFields[0].Descriptor()
	// user.DefaultUserid holds the default value on creation for the userid field.
	user.DefaultUserid = userDescUserid.Default.(string)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescMandantid is the schema descriptor for mandantid field.
	userDescMandantid := userFields[2].Descriptor()
	// user.DefaultMandantid holds the default value on creation for the mandantid field.
	user.DefaultMandantid = userDescMandantid.Default.(string)
	// userDescRoles is the schema descriptor for roles field.
	userDescRoles := userFields[3].Descriptor()
	// user.DefaultRoles holds the default value on creation for the roles field.
	user.DefaultRoles = userDescRoles.Default.(string)
}
