// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// TimersColumns holds the columns for the "timers" table.
	TimersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "projectid", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "tags", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "timer_start", Type: field.TypeTime, Nullable: true},
		{Name: "timer_end", Type: field.TypeTime, Nullable: true},
		{Name: "elapsed_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "is_billed", Type: field.TypeBool, Nullable: true},
		{Name: "is_running", Type: field.TypeBool, Nullable: true},
		{Name: "userid", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "mandantid", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// TimersTable holds the schema information for the "timers" table.
	TimersTable = &schema.Table{
		Name:        "timers",
		Columns:     TimersColumns,
		PrimaryKey:  []*schema.Column{TimersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TimersTable,
	}
)

func init() {
}
