apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: obiwan007/frontend:latest
          imagePullPolicy: "Always"
          env:
            - name: GRAPHQL
              value: "http://gqlsrv:8090"
            - name: GQLSRV
              value: "gqlsrv"
            - name: ZIPKIN
              value: "http://zipkin:9411"
          ports:
            - name: frontend
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
  type: NodePort
