apiVersion: v1
kind: Service
metadata:
  name: new
  namespace: obiwan007
  selfLink: /api/v1/namespaces/obiwan007/services/new
  uid: 8058647a-de2d-4b1f-814d-bab679bf8bcb
  resourceVersion: "349592944"
  creationTimestamp: 2020-04-22T12:45:22Z
  labels:
    app: myapp
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: api
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
