apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm
  DBCONNECTIONTIMER: "postgres://user:password@94.199.214.175:5432/timer?sslmode=disable"
  DBCONNECTIONPROJECT: "postgres://user:password@94.199.214.175:5432/project?sslmode=disable"
  DBCONNECTIONCLIENT: "postgres://user:password@94.199.214.175:5432/client?sslmode=disable"
  CLIENTID: <SECRET>
  CLIENTSECRET: <SECRET>
  REDIRECT: https://localhost:3001/auth/callback
  GRAPHQL: http://gqlsrv:8090
  GQLSRV: "gqlsrv"
  ZIPKIN: http://zipkin:9411
