apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: jaegertracing/all-in-one:1.17
          ports:
            - containerPort: 9411
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - name: http
      port: 16686
    - name: zipkin
      port: 9411
  type: NodePort
