// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
type OrderRequest struct {
	// The name of the User.
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer             string                    `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Status               string                    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedOn            int64                     `protobuf:"varint,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	OrderItems           []*OrderRequest_OrderItem `protobuf:"bytes,7,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderRequest) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *OrderRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderRequest) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *OrderRequest) GetOrderItems() []*OrderRequest_OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

type OrderRequest_OrderItem struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest_OrderItem) Reset()         { *m = OrderRequest_OrderItem{} }
func (m *OrderRequest_OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderRequest_OrderItem) ProtoMessage()    {}
func (*OrderRequest_OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0, 0}
}

func (m *OrderRequest_OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest_OrderItem.Unmarshal(m, b)
}
func (m *OrderRequest_OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderRequest_OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest_OrderItem.Merge(m, src)
}
func (m *OrderRequest_OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderRequest_OrderItem.Size(m)
}
func (m *OrderRequest_OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest_OrderItem proto.InternalMessageInfo

func (m *OrderRequest_OrderItem) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OrderRequest_OrderItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderRequest_OrderItem) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *OrderRequest_OrderItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderRequest)(nil), "pb.OrderRequest")
	proto.RegisterType((*OrderRequest_OrderItem)(nil), "pb.OrderRequest.OrderItem")
	proto.RegisterType((*OrderResponse)(nil), "pb.OrderResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0xa4, 0xfd, 0xaa, 0x99, 0xaa, 0xd4, 0x3d, 0x48, 0x88, 0x08, 0xa5, 0x17, 0x7b,
	0x0a, 0x58, 0xbd, 0x79, 0xab, 0x5e, 0x3c, 0xb5, 0x44, 0x3c, 0x97, 0x24, 0x3b, 0x94, 0x05, 0xb3,
	0xbb, 0xdd, 0x9d, 0x15, 0xfd, 0x33, 0xfe, 0x56, 0xd9, 0xed, 0x1a, 0x82, 0xb7, 0x79, 0x9f, 0x85,
	0xc9, 0xf3, 0x66, 0x60, 0xaa, 0x0c, 0x47, 0x53, 0x6a, 0xa3, 0x48, 0xb1, 0x54, 0x37, 0x8b, 0xef,
	0x14, 0xce, 0x36, 0x9e, 0x55, 0x78, 0x70, 0x68, 0x89, 0x5d, 0x40, 0x2a, 0x78, 0x9e, 0xcc, 0x93,
	0x65, 0x56, 0xa5, 0x82, 0xb3, 0x02, 0x4e, 0x5b, 0x67, 0x49, 0x75, 0x68, 0xf2, 0x34, 0xd0, 0x3e,
	0xb3, 0x2b, 0x98, 0x58, 0xaa, 0xc9, 0xd9, 0x7c, 0x14, 0x5e, 0x62, 0x62, 0x37, 0x00, 0xad, 0xc1,
	0x9a, 0x90, 0xef, 0x94, 0xcc, 0xc7, 0xf3, 0x64, 0x39, 0xaa, 0xb2, 0x48, 0x36, 0x92, 0x3d, 0x46,
	0x8d, 0x9d, 0x20, 0xec, 0x6c, 0x7e, 0x32, 0x1f, 0x2d, 0xa7, 0xab, 0xa2, 0xd4, 0x4d, 0x39, 0x34,
	0x39, 0x86, 0x17, 0xc2, 0xae, 0x02, 0xf5, 0x3b, 0xda, 0x42, 0x42, 0xd6, 0x3f, 0x30, 0x06, 0xe3,
	0x56, 0x71, 0x8c, 0xba, 0x61, 0xf6, 0x4c, 0xd6, 0x1d, 0x46, 0xd9, 0x30, 0x7b, 0x21, 0x27, 0x05,
	0xed, 0xb4, 0x11, 0x2d, 0x06, 0xd9, 0xb4, 0xca, 0x3c, 0xd9, 0x7a, 0xe0, 0x3b, 0x1e, 0x5c, 0x2d,
	0x49, 0xd0, 0x57, 0xb0, 0xfd, 0x5f, 0xf5, 0x79, 0x71, 0x0b, 0xe7, 0xd1, 0xca, 0x6a, 0x25, 0x2d,
	0x0e, 0x4a, 0x27, 0xc3, 0xd2, 0xab, 0xe7, 0xf8, 0x23, 0x5f, 0xd1, 0x7c, 0xf8, 0xa5, 0x0f, 0x30,
	0x7d, 0x0a, 0x95, 0x03, 0x65, 0xb3, 0xbf, 0xfd, 0x8a, 0xcb, 0x01, 0x39, 0xee, 0x5e, 0xfc, 0x5b,
	0xdf, 0xc1, 0xb5, 0x50, 0xe5, 0xde, 0xe8, 0xb6, 0xc4, 0xcf, 0xba, 0xd3, 0xef, 0x68, 0x4b, 0xa3,
	0x1c, 0xe1, 0xde, 0x09, 0x8e, 0xeb, 0xd9, 0x9b, 0xed, 0xbf, 0xb0, 0xf5, 0x47, 0xdc, 0x26, 0xcd,
	0x24, 0x5c, 0xf3, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x26, 0xc5, 0x2f, 0x76, 0xdc, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	CreateOrder(context.Context, *OrderRequest) (*OrderResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
