// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/obiwan007/usersrv/clientsrv/api/storage/ent/client"
)

// ClientCreate is the builder for creating a Client entity.
type ClientCreate struct {
	config
	mutation *ClientMutation
	hooks    []Hook
}

// SetDescription sets the description field.
func (cc *ClientCreate) SetDescription(s string) *ClientCreate {
	cc.mutation.SetDescription(s)
	return cc
}

// SetNillableDescription sets the description field if the given value is not nil.
func (cc *ClientCreate) SetNillableDescription(s *string) *ClientCreate {
	if s != nil {
		cc.SetDescription(*s)
	}
	return cc
}

// SetName sets the name field.
func (cc *ClientCreate) SetName(s string) *ClientCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetNillableName sets the name field if the given value is not nil.
func (cc *ClientCreate) SetNillableName(s *string) *ClientCreate {
	if s != nil {
		cc.SetName(*s)
	}
	return cc
}

// SetAddress sets the address field.
func (cc *ClientCreate) SetAddress(s string) *ClientCreate {
	cc.mutation.SetAddress(s)
	return cc
}

// SetNillableAddress sets the address field if the given value is not nil.
func (cc *ClientCreate) SetNillableAddress(s *string) *ClientCreate {
	if s != nil {
		cc.SetAddress(*s)
	}
	return cc
}

// SetUserid sets the userid field.
func (cc *ClientCreate) SetUserid(s string) *ClientCreate {
	cc.mutation.SetUserid(s)
	return cc
}

// SetNillableUserid sets the userid field if the given value is not nil.
func (cc *ClientCreate) SetNillableUserid(s *string) *ClientCreate {
	if s != nil {
		cc.SetUserid(*s)
	}
	return cc
}

// SetMandantid sets the mandantid field.
func (cc *ClientCreate) SetMandantid(s string) *ClientCreate {
	cc.mutation.SetMandantid(s)
	return cc
}

// SetNillableMandantid sets the mandantid field if the given value is not nil.
func (cc *ClientCreate) SetNillableMandantid(s *string) *ClientCreate {
	if s != nil {
		cc.SetMandantid(*s)
	}
	return cc
}

// Save creates the Client in the database.
func (cc *ClientCreate) Save(ctx context.Context) (*Client, error) {
	if _, ok := cc.mutation.Description(); !ok {
		v := client.DefaultDescription
		cc.mutation.SetDescription(v)
	}
	if _, ok := cc.mutation.Name(); !ok {
		v := client.DefaultName
		cc.mutation.SetName(v)
	}
	if _, ok := cc.mutation.Address(); !ok {
		v := client.DefaultAddress
		cc.mutation.SetAddress(v)
	}
	if _, ok := cc.mutation.Userid(); !ok {
		v := client.DefaultUserid
		cc.mutation.SetUserid(v)
	}
	if _, ok := cc.mutation.Mandantid(); !ok {
		v := client.DefaultMandantid
		cc.mutation.SetMandantid(v)
	}
	var (
		err  error
		node *Client
	)
	if len(cc.hooks) == 0 {
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ClientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cc.mutation = mutation
			node, err = cc.sqlSave(ctx)
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			mut = cc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ClientCreate) SaveX(ctx context.Context) *Client {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cc *ClientCreate) sqlSave(ctx context.Context) (*Client, error) {
	var (
		c     = &Client{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: client.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: client.FieldID,
			},
		}
	)
	if value, ok := cc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: client.FieldDescription,
		})
		c.Description = value
	}
	if value, ok := cc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: client.FieldName,
		})
		c.Name = value
	}
	if value, ok := cc.mutation.Address(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: client.FieldAddress,
		})
		c.Address = value
	}
	if value, ok := cc.mutation.Userid(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: client.FieldUserid,
		})
		c.Userid = value
	}
	if value, ok := cc.mutation.Mandantid(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: client.FieldMandantid,
		})
		c.Mandantid = value
	}
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	c.ID = int(id)
	return c, nil
}
