// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"

	"github.com/obiwan007/usersrv/clientsrv/api/storage/ent/client"

	"github.com/facebookincubator/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeClient = "Client"
)

// ClientMutation represents an operation that mutate the Clients
// nodes in the graph.
type ClientMutation struct {
	config
	op            Op
	typ           string
	id            *int
	description   *string
	name          *string
	address       *string
	userid        *string
	mandantid     *string
	clearedFields map[string]struct{}
}

var _ ent.Mutation = (*ClientMutation)(nil)

// newClientMutation creates new mutation for $n.Name.
func newClientMutation(c config, op Op) *ClientMutation {
	return &ClientMutation{
		config:        c,
		op:            op,
		typ:           TypeClient,
		clearedFields: make(map[string]struct{}),
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ClientMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ClientMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *ClientMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetDescription sets the description field.
func (m *ClientMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the description value in the mutation.
func (m *ClientMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// ResetDescription reset all changes of the description field.
func (m *ClientMutation) ResetDescription() {
	m.description = nil
}

// SetName sets the name field.
func (m *ClientMutation) SetName(s string) {
	m.name = &s
}

// Name returns the name value in the mutation.
func (m *ClientMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// ResetName reset all changes of the name field.
func (m *ClientMutation) ResetName() {
	m.name = nil
}

// SetAddress sets the address field.
func (m *ClientMutation) SetAddress(s string) {
	m.address = &s
}

// Address returns the address value in the mutation.
func (m *ClientMutation) Address() (r string, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// ClearAddress clears the value of address.
func (m *ClientMutation) ClearAddress() {
	m.address = nil
	m.clearedFields[client.FieldAddress] = struct{}{}
}

// AddressCleared returns if the field address was cleared in this mutation.
func (m *ClientMutation) AddressCleared() bool {
	_, ok := m.clearedFields[client.FieldAddress]
	return ok
}

// ResetAddress reset all changes of the address field.
func (m *ClientMutation) ResetAddress() {
	m.address = nil
	delete(m.clearedFields, client.FieldAddress)
}

// SetUserid sets the userid field.
func (m *ClientMutation) SetUserid(s string) {
	m.userid = &s
}

// Userid returns the userid value in the mutation.
func (m *ClientMutation) Userid() (r string, exists bool) {
	v := m.userid
	if v == nil {
		return
	}
	return *v, true
}

// ClearUserid clears the value of userid.
func (m *ClientMutation) ClearUserid() {
	m.userid = nil
	m.clearedFields[client.FieldUserid] = struct{}{}
}

// UseridCleared returns if the field userid was cleared in this mutation.
func (m *ClientMutation) UseridCleared() bool {
	_, ok := m.clearedFields[client.FieldUserid]
	return ok
}

// ResetUserid reset all changes of the userid field.
func (m *ClientMutation) ResetUserid() {
	m.userid = nil
	delete(m.clearedFields, client.FieldUserid)
}

// SetMandantid sets the mandantid field.
func (m *ClientMutation) SetMandantid(s string) {
	m.mandantid = &s
}

// Mandantid returns the mandantid value in the mutation.
func (m *ClientMutation) Mandantid() (r string, exists bool) {
	v := m.mandantid
	if v == nil {
		return
	}
	return *v, true
}

// ClearMandantid clears the value of mandantid.
func (m *ClientMutation) ClearMandantid() {
	m.mandantid = nil
	m.clearedFields[client.FieldMandantid] = struct{}{}
}

// MandantidCleared returns if the field mandantid was cleared in this mutation.
func (m *ClientMutation) MandantidCleared() bool {
	_, ok := m.clearedFields[client.FieldMandantid]
	return ok
}

// ResetMandantid reset all changes of the mandantid field.
func (m *ClientMutation) ResetMandantid() {
	m.mandantid = nil
	delete(m.clearedFields, client.FieldMandantid)
}

// Op returns the operation name.
func (m *ClientMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Client).
func (m *ClientMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *ClientMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.description != nil {
		fields = append(fields, client.FieldDescription)
	}
	if m.name != nil {
		fields = append(fields, client.FieldName)
	}
	if m.address != nil {
		fields = append(fields, client.FieldAddress)
	}
	if m.userid != nil {
		fields = append(fields, client.FieldUserid)
	}
	if m.mandantid != nil {
		fields = append(fields, client.FieldMandantid)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *ClientMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case client.FieldDescription:
		return m.Description()
	case client.FieldName:
		return m.Name()
	case client.FieldAddress:
		return m.Address()
	case client.FieldUserid:
		return m.Userid()
	case client.FieldMandantid:
		return m.Mandantid()
	}
	return nil, false
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *ClientMutation) SetField(name string, value ent.Value) error {
	switch name {
	case client.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case client.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case client.FieldAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	case client.FieldUserid:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserid(v)
		return nil
	case client.FieldMandantid:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMandantid(v)
		return nil
	}
	return fmt.Errorf("unknown Client field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *ClientMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *ClientMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *ClientMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Client numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *ClientMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(client.FieldAddress) {
		fields = append(fields, client.FieldAddress)
	}
	if m.FieldCleared(client.FieldUserid) {
		fields = append(fields, client.FieldUserid)
	}
	if m.FieldCleared(client.FieldMandantid) {
		fields = append(fields, client.FieldMandantid)
	}
	return fields
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *ClientMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *ClientMutation) ClearField(name string) error {
	switch name {
	case client.FieldAddress:
		m.ClearAddress()
		return nil
	case client.FieldUserid:
		m.ClearUserid()
		return nil
	case client.FieldMandantid:
		m.ClearMandantid()
		return nil
	}
	return fmt.Errorf("unknown Client nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *ClientMutation) ResetField(name string) error {
	switch name {
	case client.FieldDescription:
		m.ResetDescription()
		return nil
	case client.FieldName:
		m.ResetName()
		return nil
	case client.FieldAddress:
		m.ResetAddress()
		return nil
	case client.FieldUserid:
		m.ResetUserid()
		return nil
	case client.FieldMandantid:
		m.ResetMandantid()
		return nil
	}
	return fmt.Errorf("unknown Client field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *ClientMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *ClientMutation) AddedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *ClientMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *ClientMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *ClientMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *ClientMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *ClientMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Client unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *ClientMutation) ResetEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Client edge %s", name)
}
