// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/obiwan007/usersrv/clientsrv/api/storage/ent/schema"
	"github.com/obiwan007/usersrv/clientsrv/api/storage/ent/timerclient"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	timerclientFields := schema.TimerClient{}.Fields()
	_ = timerclientFields
	// timerclientDescDescription is the schema descriptor for description field.
	timerclientDescDescription := timerclientFields[0].Descriptor()
	// timerclient.DefaultDescription holds the default value on creation for the description field.
	timerclient.DefaultDescription = timerclientDescDescription.Default.(string)
	// timerclientDescName is the schema descriptor for name field.
	timerclientDescName := timerclientFields[1].Descriptor()
	// timerclient.DefaultName holds the default value on creation for the name field.
	timerclient.DefaultName = timerclientDescName.Default.(string)
	// timerclientDescAddress is the schema descriptor for address field.
	timerclientDescAddress := timerclientFields[2].Descriptor()
	// timerclient.DefaultAddress holds the default value on creation for the address field.
	timerclient.DefaultAddress = timerclientDescAddress.Default.(string)
	// timerclientDescUserid is the schema descriptor for userid field.
	timerclientDescUserid := timerclientFields[3].Descriptor()
	// timerclient.DefaultUserid holds the default value on creation for the userid field.
	timerclient.DefaultUserid = timerclientDescUserid.Default.(string)
	// timerclientDescMandantid is the schema descriptor for mandantid field.
	timerclientDescMandantid := timerclientFields[4].Descriptor()
	// timerclient.DefaultMandantid holds the default value on creation for the mandantid field.
	timerclient.DefaultMandantid = timerclientDescMandantid.Default.(string)
}
