// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/obiwan007/usersrv/clientsrv/api/storage/ent/predicate"
	"github.com/obiwan007/usersrv/clientsrv/api/storage/ent/timerclient"
)

// TimerClientDelete is the builder for deleting a TimerClient entity.
type TimerClientDelete struct {
	config
	hooks      []Hook
	mutation   *TimerClientMutation
	predicates []predicate.TimerClient
}

// Where adds a new predicate to the delete builder.
func (tcd *TimerClientDelete) Where(ps ...predicate.TimerClient) *TimerClientDelete {
	tcd.predicates = append(tcd.predicates, ps...)
	return tcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tcd *TimerClientDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tcd.hooks) == 0 {
		affected, err = tcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TimerClientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tcd.mutation = mutation
			affected, err = tcd.sqlExec(ctx)
			return affected, err
		})
		for i := len(tcd.hooks) - 1; i >= 0; i-- {
			mut = tcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcd *TimerClientDelete) ExecX(ctx context.Context) int {
	n, err := tcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tcd *TimerClientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: timerclient.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: timerclient.FieldID,
			},
		},
	}
	if ps := tcd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tcd.driver, _spec)
}

// TimerClientDeleteOne is the builder for deleting a single TimerClient entity.
type TimerClientDeleteOne struct {
	tcd *TimerClientDelete
}

// Exec executes the deletion query.
func (tcdo *TimerClientDeleteOne) Exec(ctx context.Context) error {
	n, err := tcdo.tcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{timerclient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tcdo *TimerClientDeleteOne) ExecX(ctx context.Context) {
	tcdo.tcd.ExecX(ctx)
}
