// Code generated by entc, DO NOT EDIT.

package timer

const (
	// Label holds the string label denoting the timer type in the database.
	Label = "timer"
	// FieldID holds the string denoting the id field in the database.
	FieldID             = "id"              // FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription    = "description"     // FieldProjectid holds the string denoting the projectid vertex property in the database.
	FieldProjectid      = "projectid"       // FieldTags holds the string denoting the tags vertex property in the database.
	FieldTags           = "tags"            // FieldTimerStart holds the string denoting the timerstart vertex property in the database.
	FieldTimerStart     = "timer_start"     // FieldTimerEnd holds the string denoting the timerend vertex property in the database.
	FieldTimerEnd       = "timer_end"       // FieldElapsedSeconds holds the string denoting the elapsedseconds vertex property in the database.
	FieldElapsedSeconds = "elapsed_seconds" // FieldIsBilled holds the string denoting the isbilled vertex property in the database.
	FieldIsBilled       = "is_billed"       // FieldIsRunning holds the string denoting the isrunning vertex property in the database.
	FieldIsRunning      = "is_running"      // FieldUserid holds the string denoting the userid vertex property in the database.
	FieldUserid         = "userid"          // FieldMandantid holds the string denoting the mandantid vertex property in the database.
	FieldMandantid      = "mandantid"

	// Table holds the table name of the timer in the database.
	Table = "timers"
)

// Columns holds all SQL columns for timer fields.
var Columns = []string{
	FieldID,
	FieldDescription,
	FieldProjectid,
	FieldTags,
	FieldTimerStart,
	FieldTimerEnd,
	FieldElapsedSeconds,
	FieldIsBilled,
	FieldIsRunning,
	FieldUserid,
	FieldMandantid,
}

var (
	// DefaultDescription holds the default value on creation for the description field.
	DefaultDescription string
	// DefaultProjectid holds the default value on creation for the projectid field.
	DefaultProjectid string
	// DefaultTags holds the default value on creation for the tags field.
	DefaultTags string
	// DefaultElapsedSeconds holds the default value on creation for the elapsedSeconds field.
	DefaultElapsedSeconds int
	// DefaultIsBilled holds the default value on creation for the IsBilled field.
	DefaultIsBilled bool
	// DefaultIsRunning holds the default value on creation for the IsRunning field.
	DefaultIsRunning bool
	// DefaultUserid holds the default value on creation for the userid field.
	DefaultUserid string
	// DefaultMandantid holds the default value on creation for the mandantid field.
	DefaultMandantid string
)
