// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "clientid", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "userid", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "mandantid", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "status", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "tags", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "team", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:        "projects",
		Columns:     ProjectsColumns,
		PrimaryKey:  []*schema.Column{ProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProjectsTable,
	}
)

func init() {
}
