// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// TimerClientsColumns holds the columns for the "timer_clients" table.
	TimerClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "address", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "userid", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "mandantid", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// TimerClientsTable holds the schema information for the "timer_clients" table.
	TimerClientsTable = &schema.Table{
		Name:        "timer_clients",
		Columns:     TimerClientsColumns,
		PrimaryKey:  []*schema.Column{TimerClientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TimerClientsTable,
	}
)

func init() {
}
