// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// ClientsColumns holds the columns for the "clients" table.
	ClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "address", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "userid", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "mandantid", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// ClientsTable holds the schema information for the "clients" table.
	ClientsTable = &schema.Table{
		Name:        "clients",
		Columns:     ClientsColumns,
		PrimaryKey:  []*schema.Column{ClientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClientsTable,
	}
)

func init() {
}
