// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)
