name: make-master

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
        env:
          DOCKER: ${{ secrets.DOCKER }}
      - name: Docker login
        run: echo ${{ secrets.DOCKER }} | docker login docker.io -u obiwan007 --password-stdin && cat out.tmp | 
      - name: Makefile
        run: make docker        

