name: make-master

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
        env:
          DOCKER: ${{ secrets.DOCKER }}
      - name: login1
        run: echo ${{ secrets.DOCKER }} > out.tmp
      - name: login11
        run: ls -la out.tmp
      - name: login2
        run: cat out.tmp | docker login docker.pkg.github.com -u obiwan007 --password-stdin        
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make all
